# Generated by Django 2.1 on 2021-09-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=20)),
                ('fromsystem', models.CharField(max_length=20)),
                ('tosystem', models.CharField(max_length=20)),
            ],
        ),
    ]
